#!/usr/bin/env bash
set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
build_dir="$script_dir/build"
mkdir -p "$build_dir"

clang --target=armeb-none-eabi -march=armv4 -marm -c \
    "$script_dir/retro3do-demo.s" -o "$build_dir/retro3do-demo.o"
ld.lld -T "$script_dir/retro3do-demo.ld" \
    "$build_dir/retro3do-demo.o" -o "$build_dir/retro3do-demo.elf"
llvm-objcopy -O binary "$build_dir/retro3do-demo.elf" \
    "$build_dir/retro3do-demo.bin"
cp "$build_dir/retro3do-demo.bin" "$build_dir/retro3do-demo-padded.rom"
dd if=/dev/zero of="$build_dir/retro3do-demo-padded.rom" bs=1 count=0 \
    seek=1048576 2>/dev/null

hash_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1"
    else
        shasum -a 256 "$1"
    fi
}

{
    echo '// Generated by demo/build-demo-rom.sh. Do not edit by hand.'
    echo '#pragma once'
    echo
    echo '#include <cstddef>'
    echo '#include <cstdint>'
    echo
    echo 'namespace retro3do {'
    xxd -i -n kDemoRomBytes "$build_dir/retro3do-demo.bin" |
        sed 's/^unsigned char /const std::uint8_t /; s/^unsigned int /const std::size_t /'
    echo '}  // namespace retro3do'
} > "$script_dir/../src/core/demo_rom_data.h"

echo "Authored bytes:"
hash_file "$build_dir/retro3do-demo.bin"
wc -c "$build_dir/retro3do-demo.bin"
echo "One-megabyte loader image:"
hash_file "$build_dir/retro3do-demo-padded.rom"
wc -c "$build_dir/retro3do-demo-padded.rom"
